services:
  lara-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lara-mcp
    restart: unless-stopped
    working_dir: /opt
    command: ["pnpm", "dev"]
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - ./src:/opt/src
      - ./.env:/opt/.env
      - ./package.json:/opt/package.json
      - ./pnpm-lock.yaml:/opt/pnpm-lock.yaml
      - ./vitest.config.ts:/opt/vitest.config.ts
      - ./nodemon.json:/opt/nodemon.json
      - ./tsconfig.json:/opt/tsconfig.json