services:
  lara-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    container_name: lara-mcp
    restart: unless-stopped
    working_dir: /opt
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env